on:
  workflow_call:
    inputs:
      jobname:
        required: true
        type: string

jobs:
  build_and_run_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Send message to Telegram if avaible
        if: success()
        run: echo 'coucou1'
      - run: ./node_modules/cypress/bin/cypress run --spec cypress/integration/${{ inputs.jobname }}_spec.js --browser chrome
      - name: Send message to Telegram if avaible
        if: success()
        run: echo 'coucou2'
